//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpoDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImpoDoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Індекс адресата.
        /// </summary>
        public static string AddresseeIndex {
            get {
                return ResourceManager.GetString("AddresseeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Індекс адресанта.
        /// </summary>
        public static string AddresserIndex {
            get {
                return ResourceManager.GetString("AddresserIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата контролю.
        /// </summary>
        public static string CheckoutDate {
            get {
                return ResourceManager.GetString("CheckoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Керівник.
        /// </summary>
        public static string CompanyDirector {
            get {
                return ResourceManager.GetString("CompanyDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ел. пошта.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформація про підприємство.
        /// </summary>
        public static string CompanyInfoTitle {
            get {
                return ResourceManager.GetString("CompanyInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЄДРПОУ.
        /// </summary>
        public static string CompanyInn {
            get {
                return ResourceManager.GetString("CompanyInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса.
        /// </summary>
        public static string CompanyLegalAddress {
            get {
                return ResourceManager.GetString("CompanyLegalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список організацій.
        /// </summary>
        public static string CompanyListTitle {
            get {
                return ResourceManager.GetString("CompanyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місто.
        /// </summary>
        public static string CompanyLocation {
            get {
                return ResourceManager.GetString("CompanyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефону.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кореспондент.
        /// </summary>
        public static string Correspondent {
            get {
                return ResourceManager.GetString("Correspondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість екземплярів.
        /// </summary>
        public static string CounterCopy {
            get {
                return ResourceManager.GetString("CounterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість аркушів.
        /// </summary>
        public static string CounterSheets {
            get {
                return ResourceManager.GetString("CounterSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати новий елемент.
        /// </summary>
        public static string CreateButtonTooltip {
            get {
                return ResourceManager.GetString("CreateButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адресат.
        /// </summary>
        public static string DocumentAddressee {
            get {
                return ResourceManager.GetString("DocumentAddressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адресант.
        /// </summary>
        public static string DocumentAddresser {
            get {
                return ResourceManager.GetString("DocumentAddresser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На контроль.
        /// </summary>
        public static string DocumentCheckout {
            get {
                return ResourceManager.GetString("DocumentCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата документа.
        /// </summary>
        public static string DocumentCreatedAt {
            get {
                return ResourceManager.GetString("DocumentCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Короткий зміст.
        /// </summary>
        public static string DocumentDescription {
            get {
                return ResourceManager.GetString("DocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконавець.
        /// </summary>
        public static string DocumentExecutor {
            get {
                return ResourceManager.GetString("DocumentExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string DocumentFile {
            get {
                return ResourceManager.GetString("DocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Індекс кореспондента.
        /// </summary>
        public static string DocumentIncomingIndex {
            get {
                return ResourceManager.GetString("DocumentIncomingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список документів.
        /// </summary>
        public static string DocumentListTitle {
            get {
                return ResourceManager.GetString("DocumentListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місцезнаходження.
        /// </summary>
        public static string DocumentLocation {
            get {
                return ResourceManager.GetString("DocumentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Носій.
        /// </summary>
        public static string DocumentMedia {
            get {
                return ResourceManager.GetString("DocumentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва докумену.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Індекс документа.
        /// </summary>
        public static string DocumentOutgoingIndex {
            get {
                return ResourceManager.GetString("DocumentOutgoingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата надходження.
        /// </summary>
        public static string DocumentReceivedAt {
            get {
                return ResourceManager.GetString("DocumentReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата відправлення.
        /// </summary>
        public static string DocumentSentAt {
            get {
                return ResourceManager.GetString("DocumentSentAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип документа.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата народження.
        /// </summary>
        public static string EmployeeDateOfBirth {
            get {
                return ResourceManager.GetString("EmployeeDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відділ.
        /// </summary>
        public static string EmployeeDepartment {
            get {
                return ResourceManager.GetString("EmployeeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ел. пошта.
        /// </summary>
        public static string EmployeeEmail {
            get {
                return ResourceManager.GetString("EmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я.
        /// </summary>
        public static string EmployeeFirstName {
            get {
                return ResourceManager.GetString("EmployeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стать.
        /// </summary>
        public static string EmployeeGender {
            get {
                return ResourceManager.GetString("EmployeeGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картка працівника.
        /// </summary>
        public static string EmployeeInfoTitle {
            get {
                return ResourceManager.GetString("EmployeeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище.
        /// </summary>
        public static string EmployeeLastName {
            get {
                return ResourceManager.GetString("EmployeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список працівників.
        /// </summary>
        public static string EmployeeListTitle {
            get {
                return ResourceManager.GetString("EmployeeListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По батькові.
        /// </summary>
        public static string EmployeeMiddleName {
            get {
                return ResourceManager.GetString("EmployeeMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефону.
        /// </summary>
        public static string EmployeePhoneNumber {
            get {
                return ResourceManager.GetString("EmployeePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата виконання.
        /// </summary>
        public static string ExecutionCompletedAt {
            get {
                return ResourceManager.GetString("ExecutionCompletedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата отримання.
        /// </summary>
        public static string ExecutionCreatedAt {
            get {
                return ResourceManager.GetString("ExecutionCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відмітка про виконання.
        /// </summary>
        public static string ExecutionResult {
            get {
                return ResourceManager.GetString("ExecutionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фільтр.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть значення....
        /// </summary>
        public static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхідний документ.
        /// </summary>
        public static string IncomingListTitle {
            get {
                return ResourceManager.GetString("IncomingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутрішній документ.
        /// </summary>
        public static string InternalListTitle {
            get {
                return ResourceManager.GetString("InternalListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку працівників закінчено.
        /// </summary>
        public static string LoadedEmployeesList {
            get {
                return ResourceManager.GetString("LoadedEmployeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку вхідних документів закінчено.
        /// </summary>
        public static string LoadedIncDocList {
            get {
                return ResourceManager.GetString("LoadedIncDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку внутрішніх документів закінчено.
        /// </summary>
        public static string LoadedIntDocList {
            get {
                return ResourceManager.GetString("LoadedIntDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку вихідних документів закінчено.
        /// </summary>
        public static string LoadedOutDocList {
            get {
                return ResourceManager.GetString("LoadedOutDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку працівників....
        /// </summary>
        public static string LoadingEmployeesList {
            get {
                return ResourceManager.GetString("LoadingEmployeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку вхідних документів....
        /// </summary>
        public static string LoadingIncDocList {
            get {
                return ResourceManager.GetString("LoadingIncDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку внутрішніх документів....
        /// </summary>
        public static string LoadingIntDocList {
            get {
                return ResourceManager.GetString("LoadingIntDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантаження списку вихідних документів....
        /// </summary>
        public static string LoadingOutDocList {
            get {
                return ResourceManager.GetString("LoadingOutDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано додання нового працівника.
        /// </summary>
        public static string LoggerAddedNewEmployee {
            get {
                return ResourceManager.GetString("LoggerAddedNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано додання нового вхідних документа.
        /// </summary>
        public static string LoggerAddedNewIncDoc {
            get {
                return ResourceManager.GetString("LoggerAddedNewIncDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано додання нового внутрішнього документа.
        /// </summary>
        public static string LoggerAddedNewIntDoc {
            get {
                return ResourceManager.GetString("LoggerAddedNewIntDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано додання нового вихідного документа.
        /// </summary>
        public static string LoggerAddedNewOutDoc {
            get {
                return ResourceManager.GetString("LoggerAddedNewOutDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відбулось оновлення даних в колекції.
        /// </summary>
        public static string LoggerCollectionUpdated {
            get {
                return ResourceManager.GetString("LoggerCollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створенно тимчасовий файл.
        /// </summary>
        public static string LoggerCreatedTempFile {
            get {
                return ResourceManager.GetString("LoggerCreatedTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відбулось заванаження IoC.
        /// </summary>
        public static string LoggerLoadedIoc {
            get {
                return ResourceManager.GetString("LoggerLoadedIoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відбулось відкриття тимчасового файлу зовнішньою програмою.
        /// </summary>
        public static string LoggerOpenTempFile {
            get {
                return ResourceManager.GetString("LoggerOpenTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відбулось друкування тимчасового файлу.
        /// </summary>
        public static string LoggerPrintTempFile {
            get {
                return ResourceManager.GetString("LoggerPrintTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відбулось оновлення рядка стану.
        /// </summary>
        public static string LoggerStatusBarUpdated {
            get {
                return ResourceManager.GetString("LoggerStatusBarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по видаленню працівника закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionRemoveEmployeeError {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveEmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по видаленню працівника.
        /// </summary>
        public static string LoggerTransactionRemoveEmployeeExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveEmployeeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по видаленню вхідних документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionRemoveIncDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveIncDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по видаленню вхідних документа.
        /// </summary>
        public static string LoggerTransactionRemoveIncDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveIncDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по видаленню внутрішнього документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionRemoveIntDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveIntDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по видаленню внутрішнього документа.
        /// </summary>
        public static string LoggerTransactionRemoveIntDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveIntDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по видаленню вихідного документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionRemoveOutDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveOutDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по видаленню вихідного документа.
        /// </summary>
        public static string LoggerTransactionRemoveOutDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionRemoveOutDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по внесенню даних працівника закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionUpdatedEmployeeError {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedEmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по внесенню даних працівника.
        /// </summary>
        public static string LoggerTransactionUpdatedEmployeeExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedEmployeeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по внесенню даних вхідних документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionUpdatedIncDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedIncDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по внесенню даних вхідних документа.
        /// </summary>
        public static string LoggerTransactionUpdatedIncDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedIncDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по внесенню даних внутрішнього документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionUpdatedIntDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedIntDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по внесенню даних внутрішнього документа.
        /// </summary>
        public static string LoggerTransactionUpdatedIntDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedIntDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакція по внесенню даних вихідного документа закінчилася з помилкою.
        /// </summary>
        public static string LoggerTransactionUpdatedOutDocError {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedOutDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконана транзакція по внесенню даних вихідного документа.
        /// </summary>
        public static string LoggerTransactionUpdatedOutDocExecuted {
            get {
                return ResourceManager.GetString("LoggerTransactionUpdatedOutDocExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано зміну даних існуючого працівника.
        /// </summary>
        public static string LoggerUpdatedEmployee {
            get {
                return ResourceManager.GetString("LoggerUpdatedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано зміну даних існуючого вхідних документа.
        /// </summary>
        public static string LoggerUpdatedIncDoc {
            get {
                return ResourceManager.GetString("LoggerUpdatedIncDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано зміну даних існуючого внутрішнього документа.
        /// </summary>
        public static string LoggerUpdatedIntDoc {
            get {
                return ResourceManager.GetString("LoggerUpdatedIntDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виконано зміну даних існуючого вихідного документа.
        /// </summary>
        public static string LoggerUpdatedOutDoc {
            get {
                return ResourceManager.GetString("LoggerUpdatedOutDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про програму.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати.
        /// </summary>
        public static string MenuItemChange {
            get {
                return ResourceManager.GetString("MenuItemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Організації.
        /// </summary>
        public static string MenuItemCompanies {
            get {
                return ResourceManager.GetString("MenuItemCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити.
        /// </summary>
        public static string MenuItemCreate {
            get {
                return ResourceManager.GetString("MenuItemCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити.
        /// </summary>
        public static string MenuItemDelete {
            get {
                return ResourceManager.GetString("MenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довідники.
        /// </summary>
        public static string MenuItemDirectories {
            get {
                return ResourceManager.GetString("MenuItemDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ.
        /// </summary>
        public static string MenuItemDocument {
            get {
                return ResourceManager.GetString("MenuItemDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правка.
        /// </summary>
        public static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Працівники.
        /// </summary>
        public static string MenuItemEmployees {
            get {
                return ResourceManager.GetString("MenuItemEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вийти.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допомога.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відкрити додаток.
        /// </summary>
        public static string OpenAttachmentButton {
            get {
                return ResourceManager.GetString("OpenAttachmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихідний документ.
        /// </summary>
        public static string OutgoingListTitle {
            get {
                return ResourceManager.GetString("OutgoingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Друкувати додаток.
        /// </summary>
        public static string PrintAttachmentButton {
            get {
                return ResourceManager.GetString("PrintAttachmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити елемент.
        /// </summary>
        public static string RemoveButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резолюція.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата резолюції.
        /// </summary>
        public static string ResolutionCreatedAt {
            get {
                return ResourceManager.GetString("ResolutionCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всього елементів:.
        /// </summary>
        public static string StatusBarElementCount {
            get {
                return ResourceManager.GetString("StatusBarElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхідні.
        /// </summary>
        public static string TabItemIncomingDocuments {
            get {
                return ResourceManager.GetString("TabItemIncomingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутрішні.
        /// </summary>
        public static string TabItemInternalDocuments {
            get {
                return ResourceManager.GetString("TabItemInternalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихідні.
        /// </summary>
        public static string TabItemOutgoingDocuments {
            get {
                return ResourceManager.GetString("TabItemOutgoingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переглянути інформацію.
        /// </summary>
        public static string ViewButtonTooltip {
            get {
                return ResourceManager.GetString("ViewButtonTooltip", resourceCulture);
            }
        }
    }
}
